### PR TITLE
provide LongFi bindings

### PR DESCRIPTION
**Pull request by lthiery**

### CODE REVIEW

**Comment by hannobraun** [comment]
Thanks for the pull request!

CI is failing. I think `cmwx1zzabz` depends on a private repository.

**Comment by lthiery** [comment]
We will be opening them shortly.

**Comment by hannobraun** [comment]
Cool. Please ping me here once that happened. Happy to merge as soon as the CI is green.

**Comment by lthiery** [comment]
I've moved the LongFi example from the longfi-device-rs to the BSC so as to remove the circular dependencies.

That being said, I have a weird linking error when I build for rust-catena in release mode.
```
note: rust-lld: error: undefined symbol: __gnu_thumb1_case_uqi
```

It appears the `__gnu_thumb1_case_uqi` results from switch statements being optimized in the LongFi C code. What's puzzling to me is the example in longfi-device-rs compiles just fine in release mode, which either implies the linking behavior is different or that the LongFi C code is being compiled differently.

Anyway, just taking note of this here. I have to work on other things now, but hope to circle back to this later.

Also, quick note: I depend on RTFM 5 beta in the example because I want to use cortex-m 0.6.1 which has the asm::delay fix for M0+.

**Comment by hannobraun** [comment]
The configuration I've seen in your repositories uses the GNU linker, while I'm using the LLVM linker here. Maybe that could be related to the linking error? Just guessing.

**Comment by lthiery** [comment]
USB is causing the build to fail?
```
error[E0277]: the trait bound `(stm32l0xx_hal::gpio::gpioa::PA11<stm32l0xx_hal::gpio::Input<stm32l0xx_hal::gpio::Floating>>, stm32l0xx_hal::gpio::gpioa::PA12<stm32l0xx_hal::gpio::Input<stm32l0xx_hal::gpio::Floating>>): stm32_usbd::target::UsbPins` is not satisfied
  --> examples/usb_echo.rs:43:15
   |
43 |     let bus = UsbBus::new(dp.USB, (usb_dm, usb_dp));
   |               ^^^^^^^^^^^ the trait `stm32_usbd::target::UsbPins` is not implemented for `(stm32l0xx_hal::gpio::gpioa::PA11<stm32l0xx_hal::gpio::Input<stm32l0xx_hal::gpio::Floating>>, stm32l0xx_hal::gpio::gpioa::PA12<stm32l0xx_hal::gpio::Input<stm32l0xx_hal::gpio::Floating>>)`
   |
   = help: the following implementations were found:
             <(stm32l0xx_hal::gpio::gpioa::PA11<stm32l0xx_hal::gpio::Input<stm32l0xx_hal::gpio::Floating>>, stm32l0xx_hal::gpio::gpioa::PA12<stm32l0xx_hal::gpio::Input<stm32l0xx_hal::gpio::Floating>>) as stm32_usbd::target::UsbPins>
   = note: required by `stm32_usbd::bus::UsbBus::<PINS>::new`
error[E0599]: no method named `force_reenumeration` found for type `&stm32_usbd::bus::UsbBus<(stm32l0xx_hal::gpio::gpioa::PA11<stm32l0xx_hal::gpio::Input<stm32l0xx_hal::gpio::Floating>>, stm32l0xx_hal::gpio::gpioa::PA12<stm32l0xx_hal::gpio::Input<stm32l0xx_hal::gpio::Floating>>)>` in the current scope
  --> examples/usb_echo.rs:59:18
   |
59 |     device.bus().force_reenumeration(|| {});
   |                  ^^^^^^^^^^^^^^^^^^^
   |
   = note: the method `force_reenumeration` exists but the following trait bounds were not satisfied:
           `(stm32l0xx_hal::gpio::gpioa::PA11<stm32l0xx_hal::gpio::Input<stm32l0xx_hal::gpio::Floating>>, stm32l0xx_hal::gpio::gpioa::PA12<stm32l0xx_hal::gpio::Input<stm32l0xx_hal::gpio::Floating>>) : stm32_usbd::target::UsbPins`
error: aborting due to 2 previous errors
Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: Could not compile `catena-4610`.
```

I can try to look into this later, but perhaps you can tell me where to look precisely

**Comment by lthiery** [comment]
It probably has a lot to do with me depending on my own stm32l0xx branch. I'll wait for RNG to land and I'll update this PR

**Comment by hannobraun** [comment]
Yeah, looks like a version mismatch to me. Unfortunately the whole situation around `stm32-usbd` is a bit of a mess, as it depends on the HAL libraries, which makes everything more complicated. I'm going to fix that, but I don't think I can get to it soon (certainly not before RustFest).

Basically, you need to depend on exactly the same HAL version that `stm32-usbd` depends on. If that's not possible, you need to replace the HAL version in the whole dependency tree using a `[patch]` section in Cargo.toml.

Something like this should work: https://github.com/braun-embedded/rust-catena-4610/pull/5/files#diff-80398c5faae3c069e4e6aa2ed11b28c0L24-L27

**Comment by hannobraun** [comment]
@lthiery Not sure what the status of this is right now. Just wanted to note there's #11, which updates the USB stuff. Might make sense to base your PR on that.

**Comment by hannobraun** [comment]
I've rebased this branch and fixed any build errors here: https://github.com/hannobraun/rust-catena-4610.git

I'm not submitting this myself, as I didn't test it. I just need a fork that is up-to-date to get my USB work in Detox unstuck.

**Comment by hannobraun** [comment]
Superseded by #13.

**Pull request closed without merging**
